### PR TITLE
Add manual testing instructions

### PR DESCRIPTION
**Pull request by gregeinfrank**
Add instructions on how to test locally with real data

Pull Request synchronized with [Asana task](https://app.asana.com/0/0/1204624534727854)

### CODE REVIEW

**Comment by gregeinfrank** [comment]
@rpinkerton  - Assigning to you to follow and let me know if these instructions are helpful to get some manual testing up and running

**Comment by rpinkerton** [comment]
Thanks! This is exactly what I was looking for! I'll leave some comments and approve after I give it a try myself :D

**Review by rpinkerton — APPROVED** [review]
Worked like a charm! https://app.graphite.dev/github/pr/Asana/SGTM/146/Graphite-Don-t-autosubscribe-team-reviewers-to-SGTM-tasks

Two issues I ran into (which aren't directly related to what you wrote up here but might be worth adding/looking into)

1. Running the tests directly a la `python ./test/github/models/test_pull_request.py` didn't work and instead failed with an import error (something wrong with the module or environment setup?)
2. I'm still not sure how to test feature flags, I just totally cargo-culted the approach based on other PRs that added them

**Comment by rpinkerton** [comment]
New unit test instructions worked like a charm, thanks!

**Pull request merged**
